import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/providers";


export const metadata: Metadata = {
  title: "Mavio | follow streamers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
